### ISSUE TITLE
Subideology Icons don't appear [Fix included]

### ISSUE THREAD

**Issue by MosChicken** [maldun/autobahn#2]
(This is for the KX Version of the Mod)
I love this mod, but there is this bug that is hard to ignore where the icons for subideologies do not appear. The loc does, but the images do not. They instead have the default icon for their ideology group (instead of say, Savinkovism, they would have the generic NatPop icon). The simple fix for this is to copy & paste the subideology interface, found in countrypoliticsview, from KX to your submod, although you'd need to update this every time KX adds new subideologies. I already got it working on my end, so if this isn't clear enough I could try to explain it more.

**Comment by maldun** [comment]
@MosChicken  Thx for this! This was definitely an oversight by me. This should now be fixed with fdd463b32b43de0340702a0cdd2bfd0f81a5d2bc

Since you fixed it already on your side I will include the patch with the next small update (maybe this weekend).

Thx again!

(Since I know now what you meant I will look out for it the next time)

**Comment by maldun** [comment]
I now removed the redundant countrypoliticsview files, as they were put into the initial release to ensure that everything is set properly. However, those files should not be necessary and removing them helps to avoid the need for seperate updates in the future. I will also include this path in the next release of the KR version.
