### ISSUE TITLE
Issue with Armor Tech Trees

### ISSUE THREAD

**Issue by TheBakedCookie** [maldun/autobahn#3]
Love this mod as it lets me play a longer game, though for some reason the tank tech trees aren't integrated into the game as it should be, I tried to reinstall and enable just these 2 mods and it still wasn't working. Attempted to have a look at all the files but to no avail. Not sure if it's a bug or intended (though there are clearly assets for the tech in AutoBahn). I hope you will have a look at this. Using both latest versions of the 2 mods.
![Screenshot 2022-07-27 115139](https://user-images.githubusercontent.com/84622306/181146810-8e3b70ff-7bd5-42f2-b24c-6a9caa9ef8e8.png)

**Comment by TheBakedCookie** [comment]
Nvm sorry for the trouble, didn't know the RT56 Tank tree is broken for NSB

**Comment by maldun** [comment]
Thanks for Reporting!

I am not 100% sure if this isn't by design, as with NSB there are a lot of indirect boosts of tank tech like the buffs you get from tank weapons. Maybe they left it that way on purpose as you still indirectly upgrade your tanks. 

Nevertheless, I will close the issue. 

Thanks for the feedback and glad you enjoy the mod!
